# Use root/example as user/password credentials
version: '3.7'

services:

  maria:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      default:
      static:
        ipv4_address: 172.40.0.10
    volumes:
      - ./data:/var/lib/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default
        
networks:
  default:
  static:
    ipam:
      driver: default
      config: 
        - subnet: 172.40.0.0/16