version: '3'

services:

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mysqldb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql

  symfony:
    image: nginx:latest
    volumes: 
      - ./server:/api
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8008:80"
    links: 
      - php
      - mysqldb

  php:
    image: php:7-fpm
    volumes: 
      - ./server:/api

  angular:
    image: node:alpine
    command: >
      sh -c "cd /app && npm install && npm run start"
    volumes:
      - ./client:/app
    ports:
      - "4200:4200"
    links: 
      - symfony